# Propose chaque mois une pull request vers develop quand une action GitHub a une nouvelle version.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: monthly
    commit-message:
      prefix: "CI"
